files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
     languages_mapping:
      android_code:
        ar: ar
        bn: bn
        bg: bg
        es-ES: es
        hi: hi
        id: in
        ms: ms
        my: my
        pt-PT: pt
        de: de
        fi: fi
        fil: fil
        fr: fr
        he: he
        it: it
        ja: ja
        km: km
        ko: ko
        lo: lo
        lt: lt
        nl: nl
        ru: ru
        th: th
        uk: uk
        vi: vi
        tr: tr
        ro: ro
        mr: mr
        pa-IN: pa
        pl: pl
        ka: ka
        fa: fa
        hu: hu
        hr: hr
        el: el
        cs: cs
        az: az
        sr-CS: sr
  - source: /app/src/main/res/values/strings_accountmanager.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
     languages_mapping:
      android_code:
        ar: ar
        bn: bn
        bg: bg
        es-ES: es
        hi: hi
        id: in
        ms: ms
        my: my
        pt-PT: pt
        de: de
        fi: fi
        fil: fil
        fr: fr
        he: he
        it: it
        ja: ja
        km: km
        ko: ko
        lo: lo
        lt: lt
        nl: nl
        ru: ru
        th: th
        uk: uk
        vi: vi
        tr: tr
        ro: ro
        mr: mr
        pa-IN: pa
        pl: pl
        ka: ka
        fa: fa
        hu: hu
        hr: hr
        el: el
        cs: cs
        az: az
        sr-CS: sr
  - source: /app/src/main/res/values/strings_accountmanager_errors.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
     languages_mapping:
      android_code:
        ar: ar
        bn: bn
        bg: bg
        es-ES: es
        hi: hi
        id: in
        ms: ms
        my: my
        pt-PT: pt
        de: de
        fi: fi
        fil: fil
        fr: fr
        he: he
        it: it
        ja: ja
        km: km
        ko: ko
        lo: lo
        lt: lt
        nl: nl
        ru: ru
        th: th
        uk: uk
        vi: vi
        tr: tr
        ro: ro
        mr: mr
        pa-IN: pa
        pl: pl
        ka: ka
        fa: fa
        hu: hu
        hr: hr
        el: el
        cs: cs
        az: az
        sr-CS: sr
  - source: /app/src/main/res/values/string_apps.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
     languages_mapping:
      android_code:
        ar: ar
        bn: bn
        bg: bg
        es-ES: es
        hi: hi
        id: in
        ms: ms
        my: my
        pt-PT: pt
        de: de
        fi: fi
        fil: fil
        fr: fr
        he: he
        it: it
        ja: ja
        km: km
        ko: ko
        lo: lo
        lt: lt
        nl: nl
        ru: ru
        th: th
        uk: uk
        vi: vi
        tr: tr
        ro: ro
        mr: mr
        pa-IN: pa
        pl: pl
        ka: ka
        fa: fa
        hu: hu
        hr: hr
        el: el
        cs: cs
        az: az
        sr-CS: sr
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
     languages_mapping:
      android_code:
        ar: ar
        bn: bn
        bg: bg
        es-ES: es
        hi: hi
        id: in
        ms: ms
        my: my
        pt-PT: pt
        de: de
        fi: fi
        fil: fil
        fr: fr
        he: he
        it: it
        ja: ja
        km: km
        ko: ko
        lo: lo
        lt: lt
        nl: nl
        ru: ru
        th: th
        uk: uk
        vi: vi
        tr: tr
        ro: ro
        mr: mr
        pa-IN: pa
        pl: pl
        ka: ka
        fa: fa
        hu: hu
        hr: hr
        el: el
        cs: cs
        az: az
        sr-CS: sr
  - source: /app/src/main/res/values/strings_settings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
     languages_mapping:
      android_code:
        ar: ar
        bn: bn
        bg: bg
        es-ES: es
        hi: hi
        id: in
        ms: ms
        my: my
        pt-PT: pt
        de: de
        fi: fi
        fil: fil
        fr: fr
        he: he
        it: it
        ja: ja
        km: km
        ko: ko
        lo: lo
        lt: lt
        nl: nl
        ru: ru
        th: th
        uk: uk
        vi: vi
        tr: tr
        ro: ro
        mr: mr
        pa-IN: pa
        pl: pl
        ka: ka
        fa: fa
        hu: hu
        hr: hr
        el: el
        cs: cs
        az: az
        sr-CS: sr
  - source: /app/src/main/res/values/strings_appstimeline.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
     languages_mapping:
      android_code:
        ar: ar
        bn: bn
        bg: bg
        es-ES: es
        hi: hi
        id: in
        ms: ms
        my: my
        pt-PT: pt
        de: de
        fi: fi
        fil: fil
        fr: fr
        he: he
        it: it
        ja: ja
        km: km
        ko: ko
        lo: lo
        lt: lt
        nl: nl
        ru: ru
        th: th
        uk: uk
        vi: vi
        tr: tr
        ro: ro
        mr: mr
        pa-IN: pa
        pl: pl
        ka: ka
        fa: fa
        hu: hu
        hr: hr
        el: el
        cs: cs
        az: az
        sr-CS: sr
  - source: /app/src/main/res/values/strings_badge.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
     languages_mapping:
      android_code:
        ar: ar
        bn: bn
        bg: bg
        es-ES: es
        hi: hi
        id: in
        ms: ms
        my: my
        pt-PT: pt
        de: de
        fi: fi
        fil: fil
        fr: fr
        he: he
        it: it
        ja: ja
        km: km
        ko: ko
        lo: lo
        lt: lt
        nl: nl
        ru: ru
        th: th
        uk: uk
        vi: vi
        tr: tr
        ro: ro
        mr: mr
        pa-IN: pa
        pl: pl
        ka: ka
        fa: fa
        hu: hu
        hr: hr
        el: el
        cs: cs
        az: az
        sr-CS: sr
