files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/strings_accountmanager.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/strings_accountmanager_errors.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/string_apps.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/strings_settings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/strings_appstimeline.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/strings_badge.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
